/* eslint-disable */
// Mock data for Smart Bid prototype

window.MOCK_BIDS = [
  {
    id: "B-2026-04812",
    bidNo: "20260512-00128",
    title: "행정안전부 전산실 노트북 일괄 구매(고성능 i7/16GB)",
    agency: "행정안전부",
    category: "전자/전산",
    budget: 412000000,
    deadline: "2026-05-22",
    daysLeft: 8,
    status: "신규",
    risk: "medium",
    riskScore: 54,
    fitScore: 87,
    suppliersAvailable: 7,
    biddersAvailable: 3,
    region: "세종",
    contractType: "협상에 의한 계약",
    items: [
      { name: "노트북 (i7-1360P, 16GB, 512GB)", qty: 220, unit: "EA" },
      { name: "도킹스테이션 USB-C", qty: 220, unit: "EA" },
    ],
    risks: [
      { level: "warn", title: "납기 30일 이내", desc: "관세 통관 지연시 위약 발생 우려" },
      { level: "info", title: "특정 모델군 요구", desc: "사양 표 기준 대체 가능 여부 확인 필요" },
      { level: "ok",   title: "제출서류 표준 양식", desc: "재사용 가능한 제출서류" },
    ],
    summary: "고사양 업무용 노트북 220대 + 도킹 일괄 납품 건. 관급 표준 사양 충족 모델 다수 확보 가능. 납기가 다소 타이트하나 재고 보유 공급사 3곳 확인."
  },
  {
    id: "B-2026-04795",
    bidNo: "20260511-00094",
    title: "한국전력공사 모니터 27인치 4K UHD 350대 구매",
    agency: "한국전력공사",
    category: "전자/전산",
    budget: 187000000,
    deadline: "2026-05-19",
    daysLeft: 5,
    status: "분석완료",
    risk: "low",
    riskScore: 22,
    fitScore: 92,
    suppliersAvailable: 11,
    biddersAvailable: 6,
    region: "전남",
    contractType: "일반경쟁입찰",
    items: [{ name: "27\" 4K UHD 모니터", qty: 350, unit: "EA" }],
    risks: [
      { level: "ok", title: "표준 규격", desc: "복수 공급사 견적 가능" },
      { level: "ok", title: "납기 여유", desc: "45일 납기" },
    ],
    summary: "표준 규격 모니터 대량 구매. 단가 경쟁이 핵심. 11개 공급사가 즉시 응답 가능 상태."
  },
  {
    id: "B-2026-04723",
    bidNo: "20260510-00071",
    title: "국방부 보안 서버랙 및 네트워크 장비 통합 구축",
    agency: "국방부",
    category: "네트워크",
    budget: 1240000000,
    deadline: "2026-05-30",
    daysLeft: 16,
    status: "공급사 응답중",
    risk: "high",
    riskScore: 78,
    fitScore: 41,
    suppliersAvailable: 2,
    biddersAvailable: 1,
    region: "서울",
    contractType: "협상에 의한 계약",
    items: [
      { name: "42U 보안 서버랙", qty: 8, unit: "EA" },
      { name: "L3 스위치 48포트", qty: 12, unit: "EA" },
      { name: "방화벽 어플라이언스", qty: 4, unit: "EA" },
    ],
    risks: [
      { level: "crit", title: "보안 인증 필수", desc: "CC 인증 + 국정원 검증 제품만 가능" },
      { level: "crit", title: "현장 실측 필요", desc: "기존 인프라와의 호환성 검증" },
      { level: "warn", title: "고가 장비", desc: "이행보증금 규모 상당" },
    ],
    summary: "국방 등급 보안 인증을 요구하는 고난이도 건. 자격을 갖춘 입찰사가 1곳만 확인되어 매칭 난이도 높음."
  },
  {
    id: "B-2026-04701",
    bidNo: "20260509-00203",
    title: "부산광역시청 회의실 영상회의 시스템 6식",
    agency: "부산광역시",
    category: "AV/영상",
    budget: 96000000,
    deadline: "2026-05-25",
    daysLeft: 11,
    status: "매칭대기",
    risk: "low",
    riskScore: 28,
    fitScore: 81,
    suppliersAvailable: 5,
    biddersAvailable: 4,
    region: "부산",
    contractType: "수의계약(소액)",
    items: [
      { name: "회의실 카메라+사운드바", qty: 6, unit: "SET" },
      { name: "회의실 디스플레이 65\"", qty: 6, unit: "EA" },
    ],
    risks: [
      { level: "ok", title: "소액 수의계약", desc: "절차 단순" },
      { level: "info", title: "설치 일정 조율 필요", desc: "관청 일정에 맞춰 야간 작업 가능성" },
    ],
    summary: "표준 영상회의 패키지. 설치 인력 확보된 입찰사 4곳 매칭 가능."
  },
  {
    id: "B-2026-04688",
    bidNo: "20260509-00188",
    title: "교육부 디지털 교과서 태블릿 1,200대 일괄 도입",
    agency: "교육부",
    category: "전자/전산",
    budget: 624000000,
    deadline: "2026-06-02",
    daysLeft: 19,
    status: "신규",
    risk: "medium",
    riskScore: 47,
    fitScore: 74,
    suppliersAvailable: 4,
    biddersAvailable: 2,
    region: "세종",
    contractType: "일반경쟁입찰",
    items: [
      { name: "교육용 태블릿 11\" Wi-Fi", qty: 1200, unit: "EA" },
      { name: "교육용 키보드 케이스", qty: 1200, unit: "EA" },
    ],
    risks: [
      { level: "warn", title: "MDM 사전 셋업 요구", desc: "1,200대 분 사전 프로비저닝" },
      { level: "info", title: "교육청별 배송", desc: "17개 시도 분산 배송" },
    ],
    summary: "대량 태블릿 + MDM 셋업 + 분산 배송 결합 건. 단가보단 운영 역량이 핵심."
  },
  {
    id: "B-2026-04654",
    bidNo: "20260508-00142",
    title: "대전광역시 CCTV 통합관제 신규 구축",
    agency: "대전광역시",
    category: "보안/관제",
    budget: 358000000,
    deadline: "2026-06-08",
    daysLeft: 25,
    status: "분석완료",
    risk: "medium",
    riskScore: 58,
    fitScore: 68,
    suppliersAvailable: 6,
    biddersAvailable: 3,
    region: "대전",
    contractType: "협상에 의한 계약",
    items: [
      { name: "5MP IP 카메라", qty: 80, unit: "EA" },
      { name: "VMS 라이선스 80ch", qty: 1, unit: "식" },
      { name: "관제 워크스테이션", qty: 4, unit: "EA" },
    ],
    risks: [
      { level: "warn", title: "기존 시스템 연동", desc: "레거시 NVR 인터페이스 분석 필요" },
      { level: "ok", title: "현장 답사 가능", desc: "사전 설명회 일정 공지됨" },
    ],
    summary: "VMS 통합과 카메라 일괄 도입. 영상보안 전문 입찰사 3곳 매칭 후보."
  },
  {
    id: "B-2026-04612",
    bidNo: "20260507-00099",
    title: "한국조폐공사 보안 USB 메모리 5,000개",
    agency: "한국조폐공사",
    category: "보안/관제",
    budget: 84000000,
    deadline: "2026-05-21",
    daysLeft: 7,
    status: "신규",
    risk: "low",
    riskScore: 18,
    fitScore: 95,
    suppliersAvailable: 9,
    biddersAvailable: 7,
    region: "대전",
    contractType: "일반경쟁입찰",
    items: [{ name: "보안 USB 32GB (지문인식)", qty: 5000, unit: "EA" }],
    risks: [{ level: "ok", title: "표준 보안인증 제품", desc: "재고 보유 공급사 다수" }],
    summary: "표준 보안 USB 대량 구매. 단가 경쟁 우위 확보 시 유력."
  },
  {
    id: "B-2026-04598",
    bidNo: "20260507-00081",
    title: "농촌진흥청 스마트팜 IoT 센서 통합 패키지",
    agency: "농촌진흥청",
    category: "IoT/센서",
    budget: 218000000,
    deadline: "2026-06-15",
    daysLeft: 32,
    status: "신규",
    risk: "high",
    riskScore: 71,
    fitScore: 38,
    suppliersAvailable: 1,
    biddersAvailable: 0,
    region: "전북",
    contractType: "협상에 의한 계약",
    items: [
      { name: "토양/대기 통합센서", qty: 240, unit: "EA" },
      { name: "엣지 게이트웨이", qty: 30, unit: "EA" },
      { name: "관제 SW (커스텀)", qty: 1, unit: "식" },
    ],
    risks: [
      { level: "crit", title: "특화 SW 개발", desc: "공고 사양에 커스텀 개발 포함" },
      { level: "crit", title: "농진청 표준 인증 요구", desc: "현재 보유 공급사 1곳" },
    ],
    summary: "특화 IoT + 커스텀 SW 결합. 입찰사 0곳 — 추천 보류."
  },
];

window.MOCK_SUPPLIERS = [
  { id: "S-001", name: "테크원 솔루션", category: "전자/전산", region: "서울", rating: 4.8, responseRate: "94%", avatar: "TS", lastResponse: "2분 전", status: "online" },
  { id: "S-002", name: "한솔디지털",   category: "전자/전산", region: "경기", rating: 4.6, responseRate: "88%", avatar: "한솔", lastResponse: "11분 전", status: "online" },
  { id: "S-003", name: "메가IT",       category: "네트워크",  region: "서울", rating: 4.5, responseRate: "76%", avatar: "MG", lastResponse: "1시간 전", status: "idle" },
  { id: "S-004", name: "스마트로직스", category: "AV/영상",   region: "부산", rating: 4.7, responseRate: "91%", avatar: "SL", lastResponse: "방금", status: "online" },
  { id: "S-005", name: "보안텍",       category: "보안/관제", region: "대전", rating: 4.9, responseRate: "97%", avatar: "보안", lastResponse: "3분 전", status: "online" },
  { id: "S-006", name: "그린IoT",      category: "IoT/센서",  region: "전북", rating: 4.3, responseRate: "62%", avatar: "GI", lastResponse: "어제", status: "off" },
];

window.MOCK_BIDDERS = [
  { id: "BD-001", name: "대신정보통신(주)", license: "정보통신공사업", region: "서울", performance: 92, capacity: "830억", capacityUsed: 0.42 },
  { id: "BD-002", name: "동부시스템(주)",   license: "정보통신공사업", region: "경기", performance: 87, capacity: "560억", capacityUsed: 0.61 },
  { id: "BD-003", name: "한국엔지니어링",   license: "전기공사업+ICT", region: "서울", performance: 84, capacity: "1,200억", capacityUsed: 0.28 },
  { id: "BD-004", name: "에이스소프트(주)", license: "SW사업자",     region: "대전", performance: 78, capacity: "320억", capacityUsed: 0.55 },
];

window.MOCK_NOTIFS = [
  { id: 1, type: "supplier", icon: "🔔", title: "테크원 솔루션 응답 도착", desc: "B-2026-04812 — 단가 ₩1,420,000 / 납기 21일", time: "방금", unread: true },
  { id: 2, type: "match",    icon: "✓",  title: "매칭 자동 추천 3건",   desc: "B-2026-04795 모니터 건 — 입찰사 6 × 공급사 11 매칭 가능", time: "8분 전", unread: true },
  { id: 3, type: "risk",     icon: "⚠",  title: "고위험 공고 신규",     desc: "B-2026-04723 국방부 — 보안 인증 필수, 검토 필요", time: "23분 전", unread: true },
  { id: 4, type: "system",   icon: "↻",  title: "공고 수집 완료",       desc: "신규 18건, 변경 4건이 추가됨", time: "1시간 전", unread: false },
  { id: 5, type: "project",  icon: "▣",  title: "프로젝트 단계 변경",   desc: "P-2026-031 — 계약 → 납품 단계로 이동", time: "2시간 전", unread: false },
  { id: 6, type: "system",   icon: "↻",  title: "Telegram 알림 발송",   desc: "공급사 7곳에 견적 요청 발송 완료", time: "3시간 전", unread: false },
];

window.MOCK_PROJECTS = {
  "공고 등록": [
    { id: "P-2026-038", title: "교육부 태블릿 1,200대", agency: "교육부", value: 624, days: 19, owner: "김민지" },
    { id: "P-2026-039", title: "농진청 스마트팜 IoT", agency: "농촌진흥청", value: 218, days: 32, owner: "박서준" },
  ],
  "공급사 확정": [
    { id: "P-2026-035", title: "행안부 노트북 220대", agency: "행정안전부", value: 412, days: 8, owner: "김민지" },
    { id: "P-2026-036", title: "한전 모니터 350대", agency: "한국전력", value: 187, days: 5, owner: "이수현" },
  ],
  "투찰 완료": [
    { id: "P-2026-032", title: "부산시 영상회의 6식", agency: "부산광역시", value: 96, days: 11, owner: "이수현" },
    { id: "P-2026-033", title: "조폐공사 보안USB", agency: "한국조폐공사", value: 84, days: 7, owner: "박서준" },
  ],
  "계약/납품": [
    { id: "P-2026-031", title: "대전 CCTV 관제구축", agency: "대전광역시", value: 358, days: 25, owner: "김민지" },
    { id: "P-2026-029", title: "외교부 회의시스템", agency: "외교부", value: 142, days: 0, owner: "이수현" },
  ],
  "정산 완료": [
    { id: "P-2026-024", title: "기상청 서버 증설", agency: "기상청", value: 268, days: 0, owner: "박서준" },
    { id: "P-2026-021", title: "통계청 노트북 80대", agency: "통계청", value: 124, days: 0, owner: "김민지" },
  ],
};

window.MOCK_AGENT_LOG = [
  { t: 0,    type: "info",  text: "[Risk Agent] 공고 B-2026-04812 분석 시작" },
  { t: 250,  type: "dim",   text: "  · 사양 파싱: i7-1360P, 16GB DDR5, 512GB NVMe" },
  { t: 500,  type: "dim",   text: "  · 단가 기준선 조회: 표준등록 모델 3개 매칭" },
  { t: 800,  type: "warn",  text: "[!] 납기 30일 — 위험도 +18 (계절성 통관지연 가능)" },
  { t: 1100, type: "dim",   text: "  · 공급사 풀 검색: category=\"전자/전산\", stock>0" },
  { t: 1400, type: "ok",    text: "[+] 즉시 응답 가능 공급사 7곳 확인" },
  { t: 1700, type: "info",  text: "[Bidder Agent] 자격 매칭 시작" },
  { t: 2000, type: "dim",   text: "  · 정보통신공사업 면허 + 실적 80점 이상 필터" },
  { t: 2300, type: "ok",    text: "[+] 입찰사 후보 3곳 (대신정보통신, 동부시스템, 한국엔지니어링)" },
  { t: 2700, type: "info",  text: "[Pricing Agent] 투찰가 시뮬레이션" },
  { t: 3000, type: "dim",   text: "  · 최근 12개월 동일 사양 낙찰 14건 분석" },
  { t: 3300, type: "ok",    text: "[=] 권장 투찰가 ₩398.4M (98.6%) — 낙찰확률 73%" },
  { t: 3600, type: "info",  text: "[Risk Agent] 분석 완료 — risk_level=medium (54/100)" },
];
